AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch Logs analytics pipeline for MCP logs using Lambda processing

Parameters:
  AnalyticsLogsBucket:
    Type: String
    Default: alphavantage-mcp-analytics-logs
    Description: S3 bucket name for MCP analytics logs
  
  LambdaLogGroupName:
    Type: String
    Description: CloudWatch log group name for the MCP Lambda function
    Default: /aws/lambda/alphavantage-mcp-server

Resources:
  # S3 bucket for analytics logs
  AnalyticsLogsBucketResource:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AnalyticsLogsBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: AnalyticsLogsLifecycle
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
            ExpirationInDays: 2555  # 7 years retention
  # Lambda function to process logs and write to S3
  LogsProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: mcp-logs-processor
      Runtime: python3.9
      Handler: logs_processor.lambda_handler
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LogsProcessorRole-mcp'
      Code: src
      Description: Process CloudWatch logs and write to S3
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          S3_BUCKET: !Ref AnalyticsLogsBucketResource

  # Permission for CloudWatch Logs to invoke Lambda
  LogsInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LogsProcessorFunction
      Action: lambda:InvokeFunction
      Principal: !Sub logs.${AWS::Region}.amazonaws.com
      SourceArn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LambdaLogGroupName}:*

  # CloudWatch Logs Subscription Filter
  MCPAnalyticsSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      LogGroupName: !Ref LambdaLogGroupName
      FilterName: mcp-analytics-filter
      FilterPattern: '"MCP_ANALYTICS"'
      DestinationArn: !GetAtt LogsProcessorFunction.Arn

Outputs:
  AnalyticsLogsBucket:
    Description: 'S3 bucket for MCP analytics logs'
    Value: !Ref AnalyticsLogsBucketResource

  LogsProcessorFunctionArn:
    Description: 'Logs processor Lambda function ARN'
    Value: !GetAtt LogsProcessorFunction.Arn