version = 0.1

[default.deploy.parameters]
stack_name = "alphavantage-mcp-server-analytics"
resolve_s3 = true
s3_prefix = "alphavantage-mcp-server-analytics"
region = "us-east-1"
confirm_changeset = true
