version = 0.1

[default.deploy.parameters]
stack_name = "alphavantage-mcp-server"
resolve_s3 = true
s3_prefix = "alphavantage-mcp-server"
region = "us-east-1"
confirm_changeset = true
parameter_overrides = "Environment=\"production\""
image_repositories = []
