AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Minimal AWS Lambda function with Streamable HTTP MCP Server

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    
Parameters:
  Environment:
    Type: String
    Default: production
    Description: Environment name
  DomainName:
    Type: String
    Description: Custom domain name for the API
  CertificateArn:
    Type: String
    Description: ACM Certificate ARN for the custom domain (must be in us-east-1)

Resources:
  CustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref DomainName
      CertificateArn: !Ref CertificateArn
      SecurityPolicy: TLS_1_2

  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref CustomDomain
      RestApiId: !Ref ServerlessRestApi
      Stage: Prod

  MCPLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        RootApi:
          Type: Api
          Properties:
            Path: /
            Method: any
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          PYTHONPATH: /var/runtime

Outputs:
  MCPApi:
    Description: "API Gateway endpoint URL for MCP function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  CustomDomainURL:
    Description: "Custom domain URL for MCP function"
    Value: !Sub "https://${DomainName}/"
  CustomDomainTarget:
    Description: "Custom domain target for DNS configuration"
    Value: !GetAtt CustomDomain.DistributionDomainName
  MCPLambdaFunction:
    Description: "MCP Lambda Function ARN"
    Value: !GetAtt MCPLambdaFunction.Arn
  MCPLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for MCP function"
    Value: !GetAtt MCPLambdaFunctionRole.Arn